#!/usr/bin/env bash

function usage {
    echo "newpost TITLE" >&2
}

if [ $# != 1 ]; then
    usage
    exit 1
fi

if [ $1 = "--help" ] || [ $1 = "-h" ]; then
    usage
    exit 0
fi

slug=$1
# Replace '-' with ' ', uppercase first letter, append period.
title="$(tr '-' ' ' <<< ${slug^})."

# create new post
dest="_posts/$(date +%Y-%m-%d)-$slug.md"
cp "newpost-template.md" "$dest"
sed -ri "s/\{date\}/$(date -Iseconds)/" "$dest"
sed -ri "s/\{title\}/$title/" "$dest"

# tell user where it is, and open it for editing
echo "$dest"
ni "$dest"

